### ISSUE TITLE
Provide role binding examples for service account spark-operator-api-user

### ISSUE THREAD

**Issue by hiboyang** [apple/batch-processing-gateway#3]
The service account `spark-operator-api-user` used by the gateway needs certain Kubernetes permissions to talk to Spark EKS cluster API Server, e.g. creating/reading SparkApplication CRD, listing Pod, reading Pod log, etc.

Better to have some example files to show how to create those role bindings.

**Comment by yuchaoran2011** [comment]
Hi @hiboyang, thanks for your question. I believe something like the following should grant the required permissions:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-operator-api-user-crb
subjects:
  - kind: ServiceAccount
    name: spark-operator-api-user
    namespace: default
roleRef:
  kind: ClusterRole
  name: spark-operator-api-user-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator-api-user-role
rules:
  - apiGroups:
      - ""
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - resourcequotas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - sparkapplications
      - sparkapplications/status
      - scheduledsparkapplications
      - scheduledsparkapplications/status
    verbs:
      - create
      - delete
      - get
      - deletecollection
      - list
      - patch
      - update
      - watch
```
